apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - loadgen.yaml

# Тег образу — в одному місці. Оновлення версії:
#   kustomize edit set image ...=...:v2  (або просто правка newTag тут)
images:
  - name: 832828869208.dkr.ecr.eu-central-1.amazonaws.com/mds06-ml-model
    newTag: v5
